// Generated by CoffeeScript 2.2.2
var createUser, deleteUser, fetchUser, reloadUser, updateUser;

import {
  json,
  send
} from 'micro';

import services from '../services/leancloud';

createUser = async(req, res) => {
  var body, result;
  body = (await json(req));
  return result = (await services.Person.create(body));
};

fetchUser = async(req, res) => {
  var result;
  return result = (await services.Person.fetch({
    objectId: req.params.objectId
  }));
};

updateUser = async(req, res) => {
  var body, result;
  body = (await json(req));
  return result = (await services.Person.update(body));
};

deleteUser = async(req, res) => {
  var result;
  return result = (await services.Person.delete({
    objectId: req.params.objectId
  }));
};

reloadUser = async() => {
  var result;
  return result = (await services.Person.reload());
};

export {
  createUser,
  fetchUser,
  updateUser,
  deleteUser,
  reloadUser
};
