// Generated by CoffeeScript 2.2.2
var generateToken, refreshToken, verifyToken;

import jwt from 'jsonwebtoken';

generateToken = (objectId, sessionToken, username) => {
  return jwt.sign({
    objectId: objectId,
    sessionToken: sessionToken,
    dateTime: Date.now()
  }, 'shhh');
};

verifyToken = (token) => {
  var decoded;
  decoded = jwt.verify(token, 'shhh');
  if ((Date.now() - decoded.dateTime) / 1000 / 60 > 1440) {
    return {
      err: {
        name: 'JsonWebTokenError',
        message: 'jwt is expired',
        code: 10001
      }
    };
  } else {
    return {
      objectId: decoded.objectId,
      sessionToken: decoded.sessionToken
    };
  }
};

refreshToken = (old_token) => {
  var decoded, newToken;
  decoded = jwt.verify(old_token, 'shhh');
  newToken = generateToken(decoded.objectId, decoded.sessionToken, decoded.username);
  return newToken;
};

export {
  verifyToken,
  refreshToken,
  generateToken
};
