// Generated by CoffeeScript 2.2.2
import {
  router,
  get,
  post,
  put
} from 'microrouter';

import {
  login,
  register,
  resetPsd
} from './api/login';

import {
  createUser
} from './api/user';

// login
// user
export default router(post('/signup', register), post('/login', login), put('/resetPsd', resetPsd), post('/user', createUser));
